services:
  nightwatch-db:
    image: postgres:18.0
    container_name: nightwatch-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12341234
    ports:
      - "5433:5432"
    volumes:
      - nightwatch-postgres-data:/var/lib/postgresql/MAJOR/docker
    networks:
      - nightwatch-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
  
  sensoringestion.presentation:
    image: sensoringestion.presentation
    build:
      context: .
      dockerfile: SensorIngestion.Presentation/Dockerfile
    container_name: sensoringestion-presentation
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__Psql=Host=nightwatch-db;Port=5432;Database=SensorIngestion;Username=postgres;Password=12341234
    ports:
      - "5001:80"
    depends_on:
      nightwatch-db:
        condition: service_healthy
    networks:
      - nightwatch-network
        
volumes:
  nightwatch-postgres-data:
    
networks:
  nightwatch-network:
    driver: bridge